apiVersion: apps/v1
kind: Deployment

metadata:
  name: ratelimex-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ratelimex

  template:
    metadata:
      labels:
        app: ratelimex

    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: ratelimex
          image: ghcr.io/anandp201/ratelimex:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: ratelimex-secrets
                key: DB_URL

          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: ratelimex-secrets
                key: DB_USERNAME

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ratelimex-secrets
                key: DB_PASSWORD

          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: ratelimex-secrets
                key: REDIS_URL

          - name: ADMIN_API_KEY
            valueFrom:
              secretKeyRef:
                name: ratelimex-secrets
                key: ADMIN_API_KEY

          - name: RATELIMEX_NAMESPACE
            valueFrom:
              secretKeyRef:
                name: ratelimex-secrets
                key: RATELIMEX_NAMESPACE
