CREATE TABLE tenant_api_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    api_path VARCHAR(512) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    failure_mode VARCHAR(32) NOT NULL,
    tenant_capacity INTEGER NOT NULL,
    tenant_refill_tokens_per_second DOUBLE PRECISION NOT NULL,
    tenant_ttl_seconds INTEGER NOT NULL,
    api_capacity INTEGER NOT NULL,
    api_refill_tokens_per_second DOUBLE PRECISION NOT NULL,
    api_ttl_seconds INTEGER NOT NULL,
    user_capacity INTEGER NOT NULL,
    user_refill_tokens_per_second DOUBLE PRECISION NOT NULL,
    user_ttl_seconds INTEGER NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_tenant_api_limits_tenant_api UNIQUE (tenant_id, api_path),
    CONSTRAINT chk_tenant_api_limits_failure_mode CHECK (failure_mode IN ('FAIL_OPEN', 'FAIL_CLOSED')),
    CONSTRAINT chk_tenant_api_limits_tenant_capacity CHECK (tenant_capacity > 0),
    CONSTRAINT chk_tenant_api_limits_tenant_refill CHECK (tenant_refill_tokens_per_second >= 0),
    CONSTRAINT chk_tenant_api_limits_tenant_ttl CHECK (tenant_ttl_seconds > 0),
    CONSTRAINT chk_tenant_api_limits_api_capacity CHECK (api_capacity > 0),
    CONSTRAINT chk_tenant_api_limits_api_refill CHECK (api_refill_tokens_per_second >= 0),
    CONSTRAINT chk_tenant_api_limits_api_ttl CHECK (api_ttl_seconds > 0),
    CONSTRAINT chk_tenant_api_limits_user_capacity CHECK (user_capacity > 0),
    CONSTRAINT chk_tenant_api_limits_user_refill CHECK (user_refill_tokens_per_second >= 0),
    CONSTRAINT chk_tenant_api_limits_user_ttl CHECK (user_ttl_seconds > 0)
);

CREATE INDEX idx_tenant_api_limits_tenant_id ON tenant_api_limits (tenant_id);
CREATE INDEX idx_tenant_api_limits_api_path ON tenant_api_limits (api_path);
